### ISSUE TITLE
Invalid dates

### ISSUE THREAD

**Issue by AcckiyGerman** [datasets/gdp-uk#5]
## Tasks
* [ ] split data into annual and quarters
* [x] fix quarters dates `1998 Q1 --> 1998-03-31` etc

## Analyse
* [ ] the source file has annual and quarters data unpivoted in one table. Probably we should split this into two files (but I don't know yet how to do this in automation)
```csv
2015,1888737
2016,1925299
1955-03-31,109967
1955-06-30,110087
```

* [x] quarters dates look like (1955 Q1 etc) while we want (1955-03-31 etc). Freeze until we implement 'find/replace' function in the automation

**Comment by AcckiyGerman** [comment]
quarters translated to formal dates via automation - dpp - find_replace feature.
